============================= test session starts =============================
platform win32 -- Python 3.9.7, pytest-7.1.2, pluggy-0.13.1
rootdir: C:\Users\kngo9\PycharmProjects\TestAPI
plugins: anyio-2.2.0
collected 4 items

[pytest]API_Get_test.py .F..                                             [100%]

================================== FAILURES ===================================
____________________________ test_expect_get_fail _____________________________

    def test_expect_get_fail():
        #tests to validate the functions return
        #We expect (e-fail) this test to fail the assertion and result in a test failure
        result = packages.GET.FetchUserData.get_all_user_email(baseurl + '/api/users/4')
>       assert type(result[1]) == type(dict) #expect assertion failure
E       AssertionError: assert <class 'list'> == <class 'type'>
E        +  where <class 'list'> = type(['eve.holt@reqres.in'])
E        +  and   <class 'type'> = type(dict)

[pytest]API_Get_test.py:31: AssertionError
=========================== short test summary info ===========================
FAILED [pytest]API_Get_test.py::test_expect_get_fail - AssertionError: assert...
========================= 1 failed, 3 passed in 1.28s =========================
